# Generated by Django 3.1.1 on 2020-09-05 17:26

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('date', models.CharField(max_length=20)),
                ('tags', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=210, size=None)),
                ('text', models.TextField(blank=True)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
    ]
