# Generated by Django 3.1.1 on 2020-09-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('date', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('code', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'News Model',
            },
        ),
        migrations.AlterModelOptions(
            name='newsdata',
            options={'verbose_name': 'Scrapy Django Item'},
        ),
    ]
